### ISSUE TITLE
Support multiple host names

### ISSUE THREAD

**Issue by varac** [jetbug123/ulauncher-ssh#10]
`ulauncher-ssh` works great *but* fails for hosts which have multiple names for `Host`:

```
Host foo.org bar.net
  Hostname 1.2.3.4
```

on the cl, i can use:

     ssh foo.org

or

    ssh bar.net

Ulauncher fails to connect to such a host because it doesn't consider this as two hosts.

**Comment by jetbug123** [comment]
I don't have much time for looking into this, but I will be glad to accept a PR :)
