### ISSUE TITLE
Request: include a brief in README.md on how to add connections

### ISSUE THREAD

**Issue by arigit** [jetbug123/ulauncher-ssh#3]
It took me a few minutes and a look at the source code to figure out how to add connections to the list that this extension displays via uLauncher (initially I was expecting this extension will have some sort of editor to add/modify/remove connections so I was lost).

I suggest adding something like the following to the README.md file of this extension repo to save people some search time and the developer some time answering basic questions

## How to add SSH Connections
This extension builds the connection list automatically by extracting "Host" entries in the current user's ~/.ssh/config file.

For examples and details on how to add entries to the ssh config file, see for instance [this link](https://www.cyberciti.biz/faq/create-ssh-config-file-on-linux-unix/)

This is a typical host entry in .ssh/config:

```
## Home nas server ##
Host nas
     HostName 192.168.1.100
     User root
```

If you have configured [passwordless ssh login](https://linuxize.com/post/how-to-setup-passwordless-ssh-login/) for this host/server, clicking on the 'nas' host entry in ulauncher will open a terminal and log you in the server automatically.

**Comment by jetbug123** [comment]
Sounds like a good idea :+1:
