### ISSUE TITLE
Duplicate connections

### ISSUE THREAD

**Issue by tzinm** [jetbug123/ulauncher-ssh#7]
First of all, great job with this extension :)

I define my ssh connections in the file `~/.ssh/config` as you can see below.

```bash
## OpenMediavault ##
Host nas
	HostName 192.168.1.25
	User tzinm
	IdentityFile ~/.ssh/id_rsa.pub
```
It works great, it appears in Ulancher and I can start a ssh session with **nas** name. The "problem" is that I have the ssh sessions duplicate, because it takes the **config** file connections and the **known_hosts** file connections.

Is there any way to solve this?

Thanks!

**Comment by jetbug123** [comment]
Thanks :)
I've pushed a fix that should deduplicate the results.
Can you try it and report if it works for you?

**Comment by tzinm** [comment]
I try to update the extension but it appears that doesn't update. Also I'll try to remove and add again from github but the outcome is the same.

In the extension information "panel" the date and the commit is from a long time ago, I show you a screenshoot.

![imagen](https://user-images.githubusercontent.com/30131390/68544334-5ef6e900-03c2-11ea-9744-7f023797f3c7.png)

Moreover, I try rebooting the system and adding the extension but it doesn't work. In the extensions preferences directory the date of the extensions db file is todays date.

![imagen](https://user-images.githubusercontent.com/30131390/68544345-7d5ce480-03c2-11ea-8542-dffdcb1f4119.png)

**Comment by jetbug123** [comment]
Hmm, it looks like you are using Ulauncher V4.
The commit 1b86aa0 was before the upgrade to the extension API 2.0, which was introduced in Ulauncher V5.
I've created a branch api-v1 with the change for the v1 extension API.
Can you try that?

**Comment by tzinm** [comment]
Yes, I am using the Ulauncher V4.

![imagen](https://user-images.githubusercontent.com/30131390/68546296-f6fdce00-03d4-11ea-945a-2778098eb3e2.png)

I have updated the extension and it continues deduplicating ssh connections.

![imagen](https://user-images.githubusercontent.com/30131390/68546325-493eef00-03d5-11ea-994b-3ae4fdbd64a4.png)

**Comment by jetbug123** [comment]
> I have updated the extension and it continues deduplicating ssh connections.

Than it works now?
Or maybe, I have not understand you correctly. 

The fix I pushed will deduplicate connections if the name e.g "host1" is in **known_hosts** and in **.ssh/config** is an host entry ("Host host1") with the same name.

Or do you want it to deduplicate the entry based on the hostname in the **.ssh/config**?

E.g:
In **known_hosts** is an entry with the IP e.g "192.168.0.2" and in your **.ssh/config** is an entry like:

Host _nas_
  Hostname 192.168.0.2

and you want that only _nas_ is showed?

**Comment by tzinm** [comment]
>Or do you want it to deduplicate the entry based on the hostname in the .ssh/config?
>
>E.g:
>In known_hosts is an entry with the IP e.g "192.168.0.2" and in your .ssh/config is an entry like:
>
>Host nas
>Hostname 192.168.0.2
>
>and you want that only nas is showed?

That is what I want :). Maybe I don't explain correct in the first comment.

My **known_hosts** format is the IP not the name. If you have **.ssh/config** file in your computer as I have, in the first ssh connection the known_hosts store the IP instead the name.

````bash
Host nas
Hostname 192.168.0.2
````

**Comment by jetbug123** [comment]
Sorry for the late answer, I've been a bit busy lately.
Can you try the branch feature/dedupe-by-hostname-api-v1?
The feature must be enabled in the settings.

**Comment by tzinm** [comment]
Hi!

I've been some days without turned on my linux computer. I've opened **Ulauncher** and I've seen a new option at the end called **Use Known_hosts** without update the extension.  I have the last version of **api-v1** branch.

![imagen](https://user-images.githubusercontent.com/30131390/69912888-406b9700-1430-11ea-969d-6286a6df0b2a.png)

I think we can close this issue :), thanks!
