### ISSUE TITLE
parse 'Include' directive in ssh config file

### ISSUE THREAD

**Issue by kkreso** [jetbug123/ulauncher-ssh#8]
Would you accept PR for this?

Here's a patch gist: [https://gist.github.com/kkreso/fab5066ac7f9f27707f744c2a3cdaac8](https://gist.github.com/kkreso/fab5066ac7f9f27707f744c2a3cdaac8)

**Comment by jetbug123** [comment]
Thanks for the PR :)
Looks good to me.
